version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - '8080:8080'
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql

#  api-test:
#    build:
#      dockerfile: Dockerfile.test
#      context: .
#  mysql-test:
#    image: mysql:8.0.19
#    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
#    ports:
#      - '3307:3306'
#    environment:
#      MYSQL_ROOT_PASSWORD: root
